name: ng-mat-app-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-app:
    uses: mahindar5/ng-pwa-app/.github/workflows/common-deploy-app.yml@main
    with:
      base-href: "/ng-mat-app/"
      npm-packages: "@mahindar5/common-lib@latest"
